# Generated by Django 5.1.4 on 2025-01-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_list', '0002_annualreport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreport',
            name='status',
        ),
        migrations.AddField(
            model_name='annualreport',
            name='achievement_description',
            field=models.TextField(null=True, verbose_name='Your Achievement there to in 100 words'),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='contribution_description',
            field=models.TextField(null=True, verbose_name='Specific contribution made to different mission of the Government like Atma Nirbhar Bharat'),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='duties_description',
            field=models.TextField(null=True, verbose_name='Brief description of duties'),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='program_description',
            field=models.TextField(null=True, verbose_name='Brief description about the program/projects/Field study'),
        ),
        migrations.AddField(
            model_name='annualreport',
            name='publications_description',
            field=models.TextField(null=True, verbose_name='Major publications/reports/Technology transferred/patents filed'),
        ),
    ]
